spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpa_playground2?serverTimezone=UTC
    username: jiwoo
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: true

logging.level:
  org.hibernate.SQL: debug # 참고: 모든 로그 출력은 가급적 로거를 통해 남겨야 한다.
                           # show_sql : 옵션은 System.out 에 하이버네이트 실행 SQL을 남긴다.
                           # org.hibernate.SQL : 옵션은 logger를 통해 하이버네이트 실행 SQL을 남긴다
#  org.hibernate.type: trace